version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: zer
      POSTGRES_DB: housing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./housing-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://myuser:zer@db:5432/housing_db
    depends_on:
      - db

volumes:
  postgres_data: