"""create houses table

Revision ID: bc3183bce420
Revises: 
Create Date: 2025-03-10 01:13:26.313116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3183bce420'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('housing_median_age', sa.Integer(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('total_bedrooms', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('median_income', sa.Float(), nullable=False),
    sa.Column('median_house_value', sa.Float(), nullable=False),
    sa.Column('ocean_proximity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    # ### end Alembic commands ###
