channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.20.3
  - cloudpickle==3.1.1
  - numpy==2.2.3
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
